# Generated by Django 5.0.6 on 2024-08-16 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_habitacion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tarifa', models.FloatField()),
                ('cant_personas', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
                ('cant_habitaciones', models.IntegerField()),
                ('cant_personas_sede', models.IntegerField()),
                ('tipo_habitaciones', models.ManyToManyField(to='hoteles_informacion.tipo_habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hoteles_informacion.hotel')),
                ('tipo_habitacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hoteles_informacion.tipo_habitacion')),
            ],
        ),
    ]
